export interface SearchOptions {
  start_cursor?: string
  page_size?: number
  filter?: {
    property: 'object'
    value: 'data_source' | 'page'
  }
  sort?: {
    direction: 'ascending' | 'descending'
    timestamp: 'last_edited_time'
  }
}

/** Standard colors used by Notion. */
export type Color =
  | 'blue'
  | 'blue_background'
  | 'brown'
  | 'brown_background'
  | 'default'
  | 'gray'
  | 'gray_background'
  | 'green'
  | 'green_background'
  | 'orange'
  | 'orange_background'
  | 'pink'
  | 'pink_background'
  | 'purple'
  | 'purple_background'
  | 'red'
  | 'red_background'
  | 'yellow'
  | 'yellow_background'

/** Standard status colors used by Notion. */
export type StatusColor =
  | 'blue'
  | 'brown'
  | 'gray'
  | 'green'
  | 'orange'
  | 'pink'
  | 'purple'
  | 'red'
  | 'yellow'

/** Standard number formats used by Notion. */
export type NumberFormat =
  | 'argentine_peso'
  | 'baht'
  | 'canadian_dollar'
  | 'chilean_peso'
  | 'colombian_peso'
  | 'danish_krone'
  | 'dirham'
  | 'dollar'
  | 'euro'
  | 'forint'
  | 'franc'
  | 'hong_kong_dollar'
  | 'koruna'
  | 'krona'
  | 'leu'
  | 'lira'
  | 'mexican_peso'
  | 'new_taiwan_dollar'
  | 'new_zealand_dollar'
  | 'norwegian_krone'
  | 'number'
  | 'number_with_commas'
  | 'percent'
  | 'peruvian_sol'
  | 'philippine_peso'
  | 'pound'
  | 'rand'
  | 'real'
  | 'ringgit'
  | 'riyal'
  | 'ruble'
  | 'rupee'
  | 'rupiah'
  | 'shekel'
  | 'singapore_dollar'
  | 'uruguayan_peso'
  | 'won'
  | 'yen'
  | 'yuan'
  | 'zloty'

/** Functions available for rollup properties in Notion. */
export type RollupFunction =
  | 'average'
  | 'checked'
  | 'count'
  | 'count_per_group'
  | 'count_values'
  | 'date_range'
  | 'earliest_date'
  | 'empty'
  | 'latest_date'
  | 'max'
  | 'median'
  | 'min'
  | 'not_empty'
  | 'percent_checked'
  | 'percent_empty'
  | 'percent_not_empty'
  | 'percent_unchecked'
  | 'range'
  | 'show_original'
  | 'show_unique'
  | 'sum'
  | 'unchecked'
  | 'unique'

/** Supported programming languages for code blocks. */
export type CodeLanguage =
  | 'abap'
  | 'arduino'
  | 'bash'
  | 'basic'
  | 'c#'
  | 'c'
  | 'c++'
  | 'clojure'
  | 'coffeescript'
  | 'css'
  | 'dart'
  | 'diff'
  | 'docker'
  | 'elixir'
  | 'elm'
  | 'erlang'
  | 'f#'
  | 'flow'
  | 'fortran'
  | 'gherkin'
  | 'glsl'
  | 'go'
  | 'graphql'
  | 'groovy'
  | 'haskell'
  | 'html'
  | 'java'
  | 'java/c/c++/c#'
  | 'javascript'
  | 'json'
  | 'julia'
  | 'kotlin'
  | 'latex'
  | 'less'
  | 'lisp'
  | 'livescript'
  | 'lua'
  | 'makefile'
  | 'markdown'
  | 'markup'
  | 'matlab'
  | 'mermaid'
  | 'nix'
  | 'objective-c'
  | 'ocaml'
  | 'pascal'
  | 'perl'
  | 'php'
  | 'plain text'
  | 'powershell'
  | 'prolog'
  | 'protobuf'
  | 'python'
  | 'r'
  | 'reason'
  | 'ruby'
  | 'rust'
  | 'sass'
  | 'scala'
  | 'scheme'
  | 'scss'
  | 'shell'
  | 'sql'
  | 'swift'
  | 'toml'
  | 'typescript'
  | 'vb.net'
  | 'verilog'
  | 'vhdl'
  | 'visual basic'
  | 'webassembly'
  | 'xml'
  | 'yaml'

/** List format types for numbered list items. */
export type ListFormat =
  | 'letters'
  | 'numbers'
  | 'roman'
